server:
  port: 8085

spring:
  application:
    name: API-GATEWAY


  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**,/api/v1/users/**
          filters:
           - AuthenticationFilter


        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/api/v1/hotels/**,/staffs/**
          filters:
           - AuthenticationFilter

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/api/v1/ratings/**
          filters:
           - AuthenticationFilter



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8084/eureka
      
      

#okta configuration for api gateway

#okta:
#  oauth2:
#    issuer: https://dev-77584981.okta.com/oauth2/default
#    audience: api://default
#    client-id: 0oa7w65a24Px9Oyms5d7
#    client-secret: JfsTTqODW21uapbbhKjW42sGzjcNs86GN7WL5dfU
#    scopes: openid, profile, email, offline_access
